### ISSUE TITLE
extractor functions for prep objects

### ISSUE THREAD

**Issue by hfrick** [ropensci-review-tools/goodpractice#107]
make objects from the prep steps, e.g., the covr object available for further use. idea by @noamross

**Comment by mpadge** [comment]
rOpenSci has now taken over maintenance of this package, as part of which we're cleaning out old issues. The checks from {goodpractice} are incorporated within our own checking system, [{pkgcheck}](https://github.com/ropensci-review-tools/pkgcheck), which does make use of separate objects from the prep steps, so I guess enough changed since this issue was opened for it to have been addressed anyway.
