### ISSUE TITLE
Consider lintr::linters_with_tags("package_development")

### ISSUE THREAD

**Issue by MichaelChirico** [ropensci-review-tools/goodpractice#174]
Hi all! Just chiming in in case this slipped your notice, but `lintr::linters_with_tags("package_development")` seems like a good fit for your default linters:

https://github.com/r-lib/lintr/blob/main/inst/lintr/linters.csv
https://lintr.r-lib.org/reference/linters_with_tags.html

**Comment by mpadge** [comment]
Thanks @MichaelChirico. The default linters here are hard-coded the following fairly restricted set:
https://github.com/ropensci-review-tools/goodpractice/blob/b215780eac3f39ff318ebd6d835ff58b6cd18880/R/prep_lintr.R#L4-L13

Most package development linters explicitly apply to `testthat`, and so arguably should not be applied by default, because `testthat` need not be used by default (notably including by rOpenSci). 

I think one of few of those that might be usefully included here might be the `package_hooks_linter`, which is currently not applied by default. If you wanted to PR that, and potentially discuss any others along the way, that'd be great. Thanks!

**Comment by MichaelChirico** [comment]
For excluding testthat linters I think we can do exclude_tags="pkg_testthat"

**Comment by MichaelChirico** [comment]
BTW if there are any lintable rules you think are missing from {lintr} feel free to file FRs!
